{ ... }:
{
  xdg.configFile."mango/noctalia/layout.conf".text = ''
    # Auto-generated by Noctalia - do not edit manually
    border_radius=12
    gappih=4
    gappiv=4
    gappoh=4
    gappov=4
    borderpx=2
  '';
}
