vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.cursorline = true                       -- 高亮光标所在行
vim.opt.expandtab = true                        -- 使用空格代替 Tab
vim.opt.tabstop = 2                             -- Tab 键宽度为 2
vim.opt.shiftwidth = 2                          -- 缩进宽度为 2
vim.opt.wrap = false                            -- 不自动换行
vim.opt.ignorecase = true                       -- 搜索忽略大小写
vim.opt.smartcase = true                        -- 当包含大写字母时，搜索区分大小写
vim.opt.hlsearch = false                        -- 搜索匹配不高亮
vim.opt.incsearch = true                        -- 增量搜索
vim.opt.clipboard = "unnamedplus"
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.opt.swapfile = false
vim.opt.shadafile = "NONE"
vim.opt.lazyredraw = true      -- 执行宏时不重绘屏幕
vim.opt.synmaxcol = 300        -- 限制语法高亮的最大列数
vim.opt.redrawtime = 1500      -- 限制语法高亮重绘时间（毫秒）
vim.opt.ttimeoutlen = 50       -- 减少按键序列超时时间
vim.opt.updatetime = 250       -- 减少 CursorHold 触发时间
